/**
 * Finding report generation (the deferred §"reporting artifact" — now that we
 * have real end-to-end findings, its shape is grounded). Produces a Markdown
 * report for a validated finding from its state + Gate 1 evidence, suitable for
 * a bug-bounty submission the operator files manually (Pluto never auto-submits
 * — Gate 2). Pure function; the caller writes the file.
 */
import type { CredentialRow, FindingRow, TargetRow, ValidationRow } from "../state/types.js";

export interface ReportInputs {
	finding: FindingRow;
	target: TargetRow;
	validations: ValidationRow[];
	credentials: CredentialRow[];
	/**
	 * Whether the finding's `validated` status is backed by a Gate-1 promotion
	 * signature the root public key accepts, with matching current associations.
	 * Defaults to false: callers must explicitly establish verification.
	 */
	trustworthy?: boolean;
}

function titleFor(finding: FindingRow, v: ValidationRow | undefined): string {
	const cls = v?.validator ?? finding.product ?? finding.service ?? "finding";
	return `${cls.replace(/_/g, " ")} on ${finding.service ?? "service"}${finding.port ? ` (port ${finding.port})` : ""}`;
}

export function buildFindingReport(inp: ReportInputs): string {
	const { finding, target, validations, credentials, trustworthy = false } = inp;
	const eligible = finding.status === "validated" || finding.status === "submitted";
	const verified = trustworthy && eligible && finding.target_id === target.id;
	const associated = validations.filter((v) => v.finding_id === finding.id);
	const passed = associated.filter((v) => v.passed === 1);
	const primary = passed[0] ?? associated[0];
	const lines: string[] = [];

	lines.push(`# ${titleFor(finding, primary)}`);
	lines.push("");
	if (!verified) {
		lines.push(
			"> **⚠ UNVERIFIED — DO NOT SUBMIT.** No verified current Gate-1 attestation " +
				"was established for this report. Verification may be unavailable, the signature " +
				"or associations invalid, or the current status ineligible. Recorded reproduction " +
				"is diagnostic evidence; establish verification before relying on it.",
		);
		lines.push("");
	}
	lines.push(`- **Finding**: #${finding.id} — status \`${finding.status}\``);
	lines.push(`- **Target**: ${target.host ?? target.label} (${target.label})`);
	lines.push(
		`- **Asset**: ${[finding.service, finding.product, finding.version].filter(Boolean).join(" ") || "n/a"}` +
			`${finding.port ? ` — ${finding.protocol ?? "tcp"}/${finding.port}` : ""}`,
	);
	if (finding.confidence != null) lines.push(`- **Reasoning-core confidence**: ${finding.confidence}`);
	if (target.scope_notes) lines.push(`- **Scope**: ${target.scope_notes}`);
	lines.push("");

	lines.push("## Summary");
	lines.push(primary?.diff_summary ?? "(no validation record)");
	lines.push("");

	if (passed.length > 0) {
		lines.push("## Validation (Gate 1 — deterministic)");
		lines.push(verified
			? "A verified attestation references a passed deterministic validation. It attests signer provenance; evidence genuineness still requires review."
			: "The ledger records the following passed deterministic validations; their attestation was not verified for this report:");
		lines.push("");
		for (const v of passed) {
			lines.push(`- **Validator**: \`${v.validator}\` — reproduced ${v.validated_at ? `at ${v.validated_at}` : ""}`);
			if (v.diff_summary) lines.push(`  - Difference observed: ${v.diff_summary}`);
			if (v.baseline_ref) lines.push(`  - Baseline evidence: \`${v.baseline_ref}\``);
			if (v.attack_ref) lines.push(`  - Attack evidence: \`${v.attack_ref}\``);
		}
		lines.push("");
	}

	if (credentials.length > 0) {
		lines.push("## Recovered credentials");
		for (const c of credentials) {
			lines.push(
				`- ${c.username ?? "(user)"}${c.secret ? ` : ${c.secret}` : ""}` +
					`${c.secret_type ? ` (${c.secret_type})` : ""}${c.source ? ` — via ${c.source}` : ""}`,
			);
		}
		lines.push("");
	}

	lines.push("## Impact");
	lines.push(
		"Review the recorded difference and referenced evidence above. This generated report does not independently establish impact, coverage, or evidence retention.",
	);
	lines.push("");
	lines.push("## Remediation");
	lines.push("_Operator to complete per class (input validation, access control, parameterization, patching, etc.)._");
	lines.push("");
	lines.push("---");
	lines.push(
		"_Generated by Cyber Pluto. This report is NOT auto-submitted — Gate 2 requires explicit human approval, " +
			"and the operator files it on the platform manually (autonomous submission is prohibited by the programs)._",
	);
	return `${lines.join("\n")}\n`;
}
